config/routes.rb
Berr::Application.routes.draw do
  get "register" => "users#new", :as => "register"  
  get "login" => "sessions#create", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resources :users  
  resources :sessions
  resources :berrs do
  	collection do
      get :all
    end
  end

  root :to => "berrs#index"  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :parent_id, :promoted, :text, :title, :user_id
  belongs_to :user

  validates_presence_of :text
	validates :tags, :length => { :minimum => 1, :maximum => 3,
    :too_long => "must be between 1 and 3 words",
    :too_short => "must be at least %{count} words" }, :if => "parent_id.nil?"
  validates :title, :presence => true, :if => "parent_id.nil?"

  has_many :children, :class_name => "Comment", :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "Comment" 

  has_many :tag_comment_links
  has_many :tags, :through => :tag_comment_links

  before_save :convert_to_markdown

  default_scope order('created_at DESC')

  def tag_string
  	output = ""

  	if tags
  		tag_names = tags.collect do |x|
  			x.name
  		end
  		output = tag_names.join(", ")
  	end

  	output
  end

  def convert_to_markdown
		markdown = Markdown.new(text)
    	self.text_converted = markdown.to_html
	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

	has_many :tag_comment_links
  has_many :comments, :through => :tag_comment_links

  has_many :tag_user_links
  has_many :user, :through => :tag_user_links
end

app/models/tag_comment_link.rb
class TagCommentLink < ActiveRecord::Base
  attr_accessible :comment_id, :tag_id

  belongs_to :comment
  belongs_to :tag
end

app/models/tag_user_link.rb
class TagUserLink < ActiveRecord::Base
  attr_accessible :tag_id, :user_id

  belongs_to :user
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password, :password_confirmation

  has_secure_password
  validates_presence_of :password, :on => :create

  has_many :comments

  has_many :tag_user_links
  has_many :tags, :through => :tag_user_links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in
  	if current_user == nil
  		flash.now.alert = "You need to log in."
  		redirect_to login_url
  	end
  end
  helper_method :admin?
end

app/controllers/berrs_controller.rb
class BerrsController < ApplicationController
	before_filter :logged_in

	def index
		#@comments = Comment.where(:deleted => false, :parent_id => nil)
		
		@comments = current_user.tags.collect(&:comments).flatten
		@comments.sort! { |a,b| b.created_at <=> a.created_at }

	end

	def all
		@comments = Comment.where(:deleted => false, :parent_id => nil).order("created_at desc")
	end

	def show
		@comment = Comment.find(params[:id])

		#@children = Comment.where(:parent_id => @comment.id)

		@new_comment = Comment.new
		@new_comment.parent_id = @comment.id
	end

	def new 
		@comment = Comment.new
	end

	def create
		# would be nice to do this via ajax as primary

		@comment = Comment.new(params[:berr])
		@comment.user_id = current_user.id

		tags = params[:tags]
    if tags
			tags.split(/,/).each do |t|
				t.strip!
				n = Tag.find_by_name(t)
				unless n 
					n = Tag.new
					n.name = t
				end
				@comment.tags << n
			end
		end

		if @comment.save
			# needs to redirect to full root of conversation, need to pass it through

			root_comment = @comment.parent
			root_comment ||= @comment

			redirect_to berr_url root_comment
		else
			render "new"
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])

		@comment.tags.destroy_all

		tags = params[:tags]
    if tags
			tags.split(/,/).each do |t|
				t.strip!
				n = Tag.find_by_name(t)
				unless n 
					n = Tag.new
					n.name = t
				end
				@comment.tags << n
			end
		end

		if @comment.update_attributes(params[:berr])
			redirect_to edit_berr_path, :notice => "comment updated"
		else
			render :edit
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		if current_user == @comment.user || current_user.admin?
			@comment.deleted = true
			#@comment.save!
			@comment.destroy
		end
		redirect_to root_url
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@jumbotron_header = "Berr"
		@jumbotron_lead = "The Tag-Based Discussion Forum"
  end

  def create
		user = User.find_by_email(params[:email])
	  if user && user.authenticate(params[:password])
	    session[:user_id] = user.id
	    redirect_to root_url, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Welcome!"
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])

    @user.tags.destroy_all

    tags = params[:tags]
    if tags
      tags.split(/,/).each do |t|
        t.strip!
        n = Tag.find_by_name(t)
        unless n 
          n = Tag.new
          n.name = t
        end
        @user.tags << n
      end
    end

    @user.save!

    redirect_to root_url

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for email, options = {}
	    options = {:alt => 'avatar', :class => 'avatar', :size => 80}.merge! options
	    id = Digest::MD5::hexdigest email.strip.downcase
	    url = 'http://www.gravatar.com/avatar/' + id + '.jpg?d=monsterid&s=' + options[:size].to_s
	    options.delete :size
	    image_tag url, options
	end

	def show_tags(tags)
		tag_string = ""
		if tags && tags.count > 0
			tags.each do |t|
				tag_string = tag_string + "<span class=\"tag label label-success\">#{t.name}</span>"
			end
		end
    tag_string
	end

	def tags_for(tags)
    tag_names = tags.collect do |x|
  			x.name
  	end
  	output = tag_names.join(", ")
	end

end

app/helpers/berrs_helper.rb
module BerrsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/berrs/_comment.html.erb
<div class="comment">
	<h3><%= gravatar_for comment.user.email, :size => 32 %><%= comment.title %></h3>
	<p><%= raw comment.text_converted %></p>
	<p><%= comment.created_at.to_s %></p>
	<p><%= raw show_tags(comment.tags) %></p>
</div>
<hr />

app/views/berrs/_fields.html.erb
  <%= render 'shared/error_messages', :object => f.object %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "span8" %>
  </div>

  <div class="field">
  	<label>Tags</label>
		<input type="hidden" id="comment-tag-input" class="span8" name="tags" style="width:300px" value="<%= f.object.tag_string %>">
  </div>
  <br /><br />

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text, :class => "span8" %>
  </div>

<script>
  $("#comment-tag-input").select2({
                  tags:[],
                  placeholder: "click and type here to add tags",
                  tokenSeparators: [",", " "],
                  maximumSelectionSize: 3
                });
  </script>

app/views/berrs/_primary_comment.html.erb
<p>
<%= time_ago_in_words(comment.created_at) + " ago" %>
<%= raw show_tags(comment.tags) %>

</p>
<div class="hero-unit">
	<h2>
		<%= comment.title %>
	</h2>
</div>

<div class="row">
	<div class="span3">
		<%= gravatar_for comment.user.email, :size => 48, :class => "img-circle" %>
		<%= comment.user.email %>
	</div>
  <div class="span8">
	<p><%= raw comment.text_converted %></p>
  </div>
</div>

app/views/berrs/_reply_comment.html.erb
<div class="well">
  <%= form_for comment, :as => :berr, :url => berrs_path do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <input name="berr[parent_id]" type="hidden" value="<%= comment.parent_id %>" />
   
    <div class="field">
      <%= f.text_area :text, :class => "span8" %>
    </div>
    <div class="actions">
      <%= f.button "Reply", :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/berrs/_user_tags.html.erb
<div id="user_tags">
	<%= form_tag user_path(current_user.id), :method => :put do %>
   <div class="field">
		<input type="hidden" id="comment-tag-input" name="tags" style="width:600px" value="<%= tags_for(current_user.tags) %>">
  	<%= submit_tag "Update", :class => "btn btn-info btn-small" %>
  </div>
  <br />
  <div class="actions"></div>
<% end %>
</div>

<script>
  $("#comment-tag-input").select2({
                  tags:[],
                  placeholder: "click and type here to add tags",
                  tokenSeparators: [",", " "],
                  maximumSelectionSize: 0
                });
  </script>

app/views/berrs/all.html.erb
<%= "There are no threads yet! Why not create one? " if @comments.count < 1 %>

<%= link_to "+ New Berr", new_berr_url, :class => "button" %>

<% @comments.each do |c| %>

<hr />
<div class="row">
	<div class="span3">
		<%= gravatar_for c.user.email, :size => 32, :class => "img-circle" %>
		<%= c.user.email %>
		<%= raw show_tags(c.tags) %>
		<br />
		<%= time_ago_in_words(c.created_at) %> ago
	</div>
  <div class="span8">
	<p>
	<%= link_to c.title, berr_path(c) %>
<br />

	<% if current_user.admin? || c.user == current_user %>
			<%= link_to "edit", edit_berr_path(c), :class => "btn btn-mini btn-danger" %>
			<%= link_to "remove", berr_path(c), :confirm => "Are you sure?", :method => :delete, :class => "btn btn-mini btn-danger" %>
		<% end %>

	</p>
  </div>
</div>

<% end %>

app/views/berrs/edit.html.erb
<%= form_for @comment, :as => :berr, :url => { :action => "update" } do |f| %>

	<%= render "fields", :f => f %>

  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/berrs/index.html.erb
<%= render "user_tags" %>

<%= "There are no threads yet! Why not create one? " if @comments.count < 1 %>

<% @comments.each do |c| %>

<hr />
<div class="row">
	<div class="span3">
		<%= gravatar_for c.user.email, :size => 32, :class => "img-circle" %>
		<%= c.user.email %>
		<%= raw show_tags(c.tags) %>
		<br />
		<%= time_ago_in_words(c.created_at) %> ago
	</div>
  <div class="span8">
	<p>
	<%= link_to c.title, berr_path(c) %>
<br />

	<% if current_user.admin? || c.user == current_user %>
			<%= link_to "edit", edit_berr_path(c), :class => "btn btn-mini btn-danger" %>
			<%= link_to "remove", berr_path(c), :confirm => "Are you sure?", :method => :delete, :class => "btn btn-mini btn-danger" %>
		<% end %>

	</p>
  </div>
</div>

<% end %>

app/views/berrs/new.html.erb
<%= form_for @comment, :as => :berr, :url => berrs_path, :html => { :class => "well" } do |f| %>

	<%= render "fields", :f => f %>

  <div class="actions"><%= f.button "Post", :class => "btn btn-danger" %></div>
<% end %>

app/views/berrs/show.html.erb
<%= render 'primary_comment', :comment => @comment %>

<% @comment.children.each do |child| %>
	<%= render 'comment', :comment => child %>
<% end %>

<%= render 'reply_comment', :comment => @new_comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Berr, tag-based discussion</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="../assets/bootstrap-responsive.css" rel="stylesheet">

      <%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
 
	 <div class="navbar navbar-fixed-top navbar-inverse">
	   <div class="navbar-inner">
	     <div class="container">
	       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	         <span class="icon-bar"></span>
	         <span class="icon-bar"></span>
	         <span class="icon-bar"></span>
	       </a>
	       <a class="brand" href="../">Berr</a>
	       <div class="nav-collapse" id="main-menu">
	    <ul class="nav">
	    	<%= raw "<li>#{link_to "+ New Berr", new_berr_url}</li>" if current_user %>
	    	<%= raw "<li>#{link_to "Conversations", root_url}</li>" if current_user %>
	    	<%= raw "<li>#{link_to "View All", all_berrs_path}</li>" if current_user %>
				<%= raw "<li>#{link_to current_user.email, root_url}</li>" if current_user %>
				<%= raw "<li>#{link_to "Register", register_url}</li>" if !current_user %>
				<%= raw "<li>#{link_to "Log in ", login_url}</li>" if !current_user %>
				<%= raw "<li>#{link_to "Log out", logout_url}</li>" if current_user %>
				<%= raw "<li>#{gravatar_for current_user.email, :size => 40}</li>" if current_user %>
	    	<li></li>
	    </ul>
	       </div>
	     </div>
	   </div>
	 </div>

    <div class="container">

			<%= yield %>

    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in object.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, :html => { :class => "well" } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.button "Register", :class => "btn btn-primary" %>
  </div>
<% end %>